# pnpm workspace 配置
# 定义 monorepo 中的子项目

packages:
  # 库项目
  - 'bit-core'
  - 'bit-ui'
  - 'bit-ecs'
  - 'bit-event'
  - 'bit-net'
  - 'bit-quadtree'
  - 'bit-assets'
  - 'bit-behaviortree'
  - 'bit-ec'
  - 'bit-condition'
  - 'bit-minigame'
  - 'bit-hotupdate'
  # 演示项目
  - 'demo'

